---
title: "Geometric Morphometrics"
output: html_notebook
---
Read CSV, Load all packages And Configure Analysis
```{r}
# read packages
source('GeneralizedProcrustesAnalysis.R')
source("StatisticalResults.R")
library('geomorph')
library('ggplot2')
```

```{r}
#read csv
df = read.csv("combined_tracings.csv")

#configure surface and species
species = readline(prompt="Will this be a human, macaque, or combined analysis?")
if (species == 'human' || species == 'macaque') {
  df = df[df$gm_or_wm == surface,]
}

surface = readline(prompt="Chose gray matter (pi) or white matter (wh)")
df = df[df$gm_or_wm == surface,]

```

Handle Outliers
```{r}
OUTLIERS = list('18_92months_human', '17_78months_human', '19_9months_human', '24_87months_human', '25_89months_human', '25_1month_macaque', '14_20months_human')
df = excludeOutliers(df, OUTLIERS)
```

Resample Sulci to 100 Points and Run Procrustes Analysis
```{r}
num = as.numeric(readline(prompt="How many landmarks are there?"))

resampled = resampleCurves(df, surface, species)
data = transformToArray(resampled, num)

GPA = procrustes(num, data)
plot3d(GPA$consensus)
```

Resample Sulci again based on Sulcal Length
```{r}
ref = findSulcalLengths(surface, species, GPA$consensus)

resampled = resampleCurves(df, surface, species, sulcalLengths=ref)
num = sumlm(ref)
data = transformToArray(resampled, num)

GPA = procrustes(num, data, sulcalLengths=ref)
plot3d(GPA$consensus)

```

PCA AND Scree Plot
```{r, echo=FALSE}
#PCA
GPA = addFactors(GPA, dimnames(data)[[3]])

PCA = gm.prcomp(GPA$coords)

summary(PCA)

#Plot pca

#create a color to age group translation table for scatterplots
colorcor = data.frame(cbind(colors = c('red', 'royalblue', 'green3', 'black'), age = c('(Infant)', '(Toddler)', '(Childhood)', '(Late Childhood)')))
brainColors = sapply(GPA$age_group, function(x) colorcor$colors[colorcor$age == x])

plot(PCA, col=brainColors, pch=c(0,1)[GPA$species], main='PCA')
legend('topright', pch=c(0,1), legend=unique(GPA$species))
legend('bottomleft', fill=colorcor$colors, cex=0.6, legend=colorcor$age)

plot(PCA, col=brainColors, pch=c(0,1)[GPA$species], main='PCA', axis1=2, axis2 =3)
legend('topright', pch=c(0,1), legend=unique(GPA$species))
legend('bottomleft', fill=colorcor$colors, cex=0.6, legend=colorcor$age)

plot(PCA, col=brainColors, pch=c(0,1)[GPA$species], main='PCA', axis1=3, axis2 =4)
legend('topright', pch=c(0,1), legend=unique(GPA$species))
legend('bottomleft', fill=colorcor$colors, cex=0.6, legend=colorcor$age)

#Scree plot
scree_data = data.frame(
  Component = 1:length(PCA$sdev),
  Variance = PCA$sdev^2 / sum(PCA$sdev^2)
)


ggplot(scree_data, aes(x = Component, y = Variance)) +
  geom_bar(stat = "identity", fill = "steelblue") +
  xlab("Principal Components") +
  ylab("Proportion of Variance Explained") +
  theme_minimal()

```
